### ISSUE TITLE
Scrapper None type object as no attribute get

### ISSUE THREAD

**Issue by Pritesh-Inexture** [AnkitKundariya/new_repo#2]
```
            if index == 1 and cell.text != ' ' and len(cell.text) > 1:
                title = cell.text
                if regex.search(title) == None:
                    td_data['name'] = title.strip()
                    td_data['url'] = cell.a.get('href')
                else:
                    continue
```

This block of code gives error ar line `cell.a.get('href')`

**Comment by AnkitKundariya** [comment]
Ok it means there May some title in 2nd cell without anchor tag. So we need
to check is if cell.a then ...
Can you please share which row range are you trying to scrap?

**Comment by Pritesh-Inexture** [comment]
I am scrapping without any range, meaning all rows

**Comment by AnkitKundariya** [comment]
can you please check now i made a fix for same.
